---
version: 3

vars:
  DB: film-cameras
  COLLECTION: cameras

tasks:
  tools:
    desc: "Install development tools"
    dir: tools
    cmds:
      - go generate -x

  mongosh:
    desc: "Run mongosh"
    cmds:
      - docker compose exec mongosh mongosh 'mongodb://localhost:27017/{{.DB}}'

  env-up:
    desc: "Start the services"
    cmds:
      - docker compose up -d

  env-down:
    desc: "Stop the services"
    cmds:
      - docker compose down

  import:
    desc: "Import sample data"
    cmds:
      - cmd: >
          docker run --volume={{.PWD}}/sample:/data/db/sample --rm -it --network=ferretdb --entrypoint=mongoimport mongo:6.0.3
          --uri 'mongodb://ferretdb/{{.DB}}'
          --db {{.DB}}
          --collection {{.COLLECTION}} 
          --type=csv 
          --headerline 
          --file=/data/db/sample/cameras.csv

  format:
    desc: "Format the code"
    cmds:
      - ./bin/gci write pkg --skip-generated -s "standard,default,prefix(github.com/w84thesun/film-camera-database)"
      - ./bin/gci write cmd --skip-generated -s "standard,default,prefix(github.com/w84thesun/film-camera-database)"

  lint:
    desc: "Lint the code"
    cmds:
      - ./bin/golangci-lint run

  run:
    desc: "Run the application"
    dir: cmd/fcdb
    cmds:
      - go run main.go --mongo-uri 'mongodb://localhost:27017/{{.DB}}' --listen-addr ':8080'